# Generated by Django 4.2.8 on 2023-12-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_usertemp_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemp',
            name='user_id',
        ),
        migrations.CreateModel(
            name='UserModelOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'create'), ('edit', 'edit')], default='create', max_length=6)),
                ('user_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.usertemp')),
            ],
        ),
    ]
