# Generated by Django 4.2.8 on 2023-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_usertemp_user_id_usermodeloperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemp',
            name='stored_time',
            field=models.DateField(auto_now=True),
        ),
    ]
