# Generated by Django 4.2.8 on 2023-12-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_usertemp_stored_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemp',
            name='stored_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
