# Generated by Django 4.2.8 on 2023-12-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/additional-images')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='uploads/title-images'),
        ),
        migrations.AddField(
            model_name='products',
            name='additional_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.additionalimage'),
        ),
    ]
