# Generated by Django 4.2.8 on 2023-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='product description', max_length=300),
            preserve_default=False,
        ),
    ]
