# Generated by Django 4.2.8 on 2023-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
