# Generated by Django 4.2.8 on 2023-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.FloatField(),
        ),
    ]
