# Generated by Django 4.2.8 on 2023-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_remove_products_rating_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='option',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='option',
            field=models.CharField(default='no option', max_length=50),
            preserve_default=False,
        ),
    ]
