# Generated by Django 4.2.8 on 2023-12-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_alter_cart_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
