# Generated by Django 4.2.8 on 2023-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_cart_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
