# Generated by Django 4.2.8 on 2023-12-16 10:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_products_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='products',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='delete',
            new_name='is_deleted',
        ),
    ]
