# Generated by Django 4.2.8 on 2023-12-16 10:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_alter_products_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
