# Generated by Django 4.2.8 on 2023-12-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_alter_category_managers_alter_subcategory_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='products',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
            ],
        ),
    ]
