# Generated by Django 4.2.8 on 2023-12-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_alter_category_name_alter_products_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
