# Generated by Django 4.2.8 on 2023-12-17 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_alter_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.products'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.products'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent_catogery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.subcategory'),
            preserve_default=False,
        ),
    ]
