# Generated by Django 4.2.8 on 2023-12-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_alter_additionalimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent_catogery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='user_app.category'),
        ),
    ]
