# Generated by Django 4.2.8 on 2023-12-25 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_alter_subcategory_parent_catogery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('phone_number', models.CharField(max_length=13)),
                ('country', models.CharField(max_length=25)),
                ('Address', models.TextField()),
                ('town_or_city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('area_code', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.usermodel')),
            ],
        ),
    ]
