# Generated by Django 4.2.8 on 2023-12-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
