# Generated by Django 4.2.8 on 2023-12-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0032_alter_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='area_code',
        ),
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
