# Generated by Django 4.2.8 on 2023-12-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_remove_address_area_code_address_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='address',
        ),
    ]
