# Generated by Django 4.2.8 on 2023-12-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0034_rename_address_address_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'holder_name', 'phone_number', 'country', 'address', 'pin_code', 'town_or_city', 'state', 'district')},
        ),
    ]
