# Generated by Django 4.2.8 on 2023-12-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0035_alter_address_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptions',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productoptions',
            name='product',
            field=models.ManyToManyField(related_name='options', to='user_app.products'),
        ),
    ]
