# Generated by Django 4.2.8 on 2023-12-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0038_alter_productoptions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='user_app.products'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='user_app.products'),
        ),
    ]
