# Generated by Django 4.2.8 on 2023-12-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0039_alter_additionalimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='datetime',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='receive_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
