# Generated by Django 4.2.8 on 2023-12-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0041_alter_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='cash-on-delivery', max_length=10),
            preserve_default=False,
        ),
    ]
