# Generated by Django 4.2.8 on 2023-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0042_orders_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
