# Generated by Django 4.2.8 on 2023-12-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0043_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[(-1, 'cancelled'), (0, 'ordered'), (1, 'packed'), (2, 'shipped'), (3, 'out for delivery'), (4, 'delivered')], max_length=50),
        ),
    ]
