# Generated by Django 4.2.8 on 2023-12-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0044_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
