# Generated by Django 4.2.8 on 2024-01-02 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0045_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.9)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('-1', 'cancelled'), ('0', 'ordered'), ('1', 'packed'), ('2', 'shipped'), ('3', 'out for delivery'), ('4', 'delivered')], max_length=50),
        ),
    ]
