# Generated by Django 4.2.8 on 2024-01-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0046_products_offer_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(height_field=720, upload_to='uploads/title-images', width_field=450),
        ),
    ]
