# Generated by Django 4.2.8 on 2024-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0048_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(height_field='height', upload_to='uploads/title-images', width_field='width'),
        ),
    ]
