# Generated by Django 4.2.8 on 2024-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0049_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.IntegerField(default=720),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='widht',
            field=models.IntegerField(default=450),
            preserve_default=False,
        ),
    ]
