# Generated by Django 4.2.8 on 2024-01-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0050_products_height_products_widht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='widht',
            new_name='width',
        ),
    ]
