# Generated by Django 4.2.8 on 2024-01-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0051_rename_widht_products_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='height',
        ),
        migrations.RemoveField(
            model_name='products',
            name='width',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='uploads/title-images'),
        ),
    ]
