# Generated by Django 4.2.8 on 2024-01-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0052_remove_products_height_remove_products_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.orders')),
            ],
        ),
    ]
