# Generated by Django 4.2.8 on 2024-01-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0053_ordercancelldetials'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancelldetials',
            name='cancelled_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
