# Generated by Django 4.2.8 on 2024-01-04 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0056_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='offer',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.9)]),
        ),
    ]
