# Generated by Django 4.2.8 on 2024-01-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0057_coupons_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='product',
            field=models.ManyToManyField(to='user_app.products'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_till',
            field=models.DateTimeField(null=True),
        ),
    ]
