# Generated by Django 4.2.8 on 2024-01-05 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0058_coupons_product_alter_coupons_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
