# Generated by Django 4.2.8 on 2024-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0061_remove_coupons_product_coupons_applied_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='minimum_purchase',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
