# Generated by Django 4.2.8 on 2024-01-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0063_coupons_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('paied', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(to='user_app.orders')),
            ],
        ),
    ]
