# Generated by Django 4.2.8 on 2024-01-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0064_ordersgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('option', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('-1', 'cancelled'), ('0', 'ordered'), ('1', 'packed'), ('2', 'shipped'), ('3', 'out for delivery'), ('4', 'delivered')], max_length=50)),
                ('receive_datetime', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.products')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='option',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='receive_datetime',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='is_paied',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrdersGroup',
        ),
        migrations.AddField(
            model_name='orders',
            name='orders',
            field=models.ManyToManyField(to='user_app.orderitem'),
        ),
    ]
