# Generated by Django 4.2.8 on 2024-01-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0065_orderitem_remove_orders_option_remove_orders_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orders',
            new_name='order_item',
        ),
    ]
