# Generated by Django 4.2.8 on 2024-01-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0066_rename_orders_orders_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_item',
            new_name='order_items',
        ),
    ]
