# Generated by Django 4.2.8 on 2024-01-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0067_rename_order_item_orders_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='is_paied',
            new_name='is_conformed',
        ),
    ]
