# Generated by Django 4.2.8 on 2024-01-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0068_rename_is_paied_orders_is_conformed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercancelldetials',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.orderitem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', to='user_app.orderitem'),
        ),
    ]
