# Generated by Django 4.2.8 on 2024-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0071_orders_razorpay_order_id_orders_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='carts',
            field=models.ManyToManyField(related_name='orders', to='user_app.cart'),
        ),
    ]
