# Generated by Django 4.2.8 on 2024-01-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0072_orders_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.usermodel')),
            ],
        ),
    ]
