# Generated by Django 4.2.8 on 2024-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0073_razorpayuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
