# Generated by Django 4.2.8 on 2024-01-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0074_usermodel_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='wish_list', to='user_app.products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.usermodel')),
            ],
        ),
    ]
