# Generated by Django 4.2.8 on 2024-01-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0075_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'cash-on-delivery'), ('Cash on delivery', 'cash-on-delivery'), ('Wallet', 'wallet')], max_length=16),
        ),
    ]
