# Generated by Django 4.2.8 on 2024-01-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0076_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cash-on-delivery', 'Cash on delivery'), ('pay-online', 'Pay Online'), ('wallet', 'Wallet')], max_length=16),
        ),
    ]
