# Generated by Django 4.2.8 on 2024-01-11 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0077_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercancelldetials',
            name='reason',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
