# Generated by Django 4.2.8 on 2024-01-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0078_alter_ordercancelldetials_reason'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='orders',
            field=models.ManyToManyField(to='user_app.orders'),
        ),
    ]
